config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "recipes#index"

  resources :recipes do
    collection do
      post :search
    end

    member do
      post "join"
    end
  end

  resources :recipe_lists, only: %i[index create show edit new] do
    member do
      post :add_recipe, to: "recipe_lists#add_recipe"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients

  has_many :recipe_list_recipes
  has_many :recipe_lists, through: :recipe_list_recipes
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/recipe_list.rb
class RecipeList < ApplicationRecord
  belongs_to :user

  has_many :recipe_list_recipes
  has_many :recipes, through: :recipe_list_recipes
end

app/models/recipe_list_recipe.rb
class RecipeListRecipe < ApplicationRecord
  belongs_to :recipe_list
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipe_lists
  has_many :recipes, through: :recipe_lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipe_lists_controller.rb
class RecipeListsController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipe_lists = current_user.recipe_lists
  end

  def show
    @recipe_list = RecipeList.find(params[:id])
    @recipes = @recipe_list.recipes
    @recipe_lists = current_user.recipe_lists
  end

  def new
    @recipe_list = RecipeList.new
  end

  def create
    @recipe_list = current_user.recipe_lists.new(recipe_list_params)
    if @recipe_list.save
      redirect_to recipe_lists_path, notice: "New recipe list created"
    else
      render :new
    end
  end

  def edit
    @recipe_list = RecipeList.find(params[:id])
  end

  def update
    if @recipe_list.update(recipe_list_params)
      redirect_to @recipe_list, notice: "Recipe list updated"
    else
      render :edit
    end
  end

  def destroy
    @recipe_list = RecipeList.find(params[:id])
    @recipe_list.destroy

    redirect_to recipe_lists_path, notice: "List deleted", status: :see_other
  end

  def add_recipe
    @recipe_list = RecipeList.find(params[:id])
    @recipe = Recipe.find(params[:recipe_id])
    selected_recipe_list = RecipeList.find(params[:recipe_list_id])
    logger.debug "recipe id: #{@recipe.id} being added to Recipe List ID: #{@recipe_list.id}"

    unless @recipe_list.recipes.include?(@recipe)
      selected_recipe_list.recipes << @recipe
      selected_recipe_list.save
      logger.debug "recipe added successfully"
      # @recipe_list.recipes << @recipe
      # @recipe_list.save
      redirect_to @recipe_list, notice: "Recipe added successfully"
    else
      redirect_to @recipe_list, alert: "Recipe is already in your list"
    end
  end

  private

  def recipe_list_params
    params.require(:recipe_list).permit(:name, :notes)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.includes(:ingredients).all
    @recipe_lists = current_user.recipe_lists
    @recipe_list = current_user.recipe_lists
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipes = Recipe.all
  end

  def search
    if params[:recipe_search].present?
      query = "%#{params[:recipe_search].downcase}%"
      @recipes = Recipe.where("LOWER(name) ILIKE ?", query)
    else
      @recipes = Recipe.all
    end

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.update("results", partial: "recipes/results", locals: { recipes: @recipes })
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/helpers/recipe_lists_helper.rb
module RecipeListsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StardewCraft</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/recipe_lists/create.html.erb
<h1>RecipeLists#create</h1>
<p>Find me in app/views/recipe_lists/create.html.erb</p>

app/views/recipe_lists/edit.html.erb
<h1>Edit Recipe List</h1>

<%= simple_form_for(@recipe_list) do |f| %>
  <%= f.input :name %>
  <%= f.input :notes %>
  <%= f.submit "Update List" %>
<% end %>

<%= link_to "Back to My Lists", recipe_lists_path %>

app/views/recipe_lists/index.html.erb
<div class="my-list-bar">
  <h1>My Lists</h1>
  <%= link_to "Create new list", new_recipe_list_path %>
</div>

<div class="list-container">
  <% if @recipe_lists.any? %>
    <ul>
      <% @recipe_lists.each do |list| %>
        <li><%= link_to list.name, recipe_list_path(list) %>
          <ul><li><%= list.notes %></li></ul>
        </li>
      <% end%>
    </ul>
    <% else %>
      <p>No recipe lists yet</p>
  <% end %>
</div>

app/views/recipe_lists/new.html.erb
<h1>New recipe list</h1>

<%= simple_form_for(@recipe_list) do |f|%>
  <%= f.input :name %>
  <%= f.input :notes %>
  <%= f.submit %>
<% end %>

app/views/recipe_lists/show.html.erb
<div class="list-bar">
  <h1><%= @recipe_list.name %></h1>
  <p><%= @recipe_list.notes %></p>
  <%= link_to "Edit list", edit_recipe_list_path(@recipe_list) %>
</div>

<div>
  <% if @recipe_list.recipes.any? %>
  <ul>
    <% @recipe_list.recipes.each do |recipe| %>
      <li><%= recipe.name %></li>
    <% end %>
  </ul>
  <% else %>
    <p>No recipes added yet</p>
  <% end %>
</div>

app/views/recipes/_results.html.erb
<div id="results">
<h1>Recipes</h1>
  <% if @recipes.any? %>
      <% @recipes.each do |recipe| %>
        <div class="recipe-item">
          <%= recipe.name %>
          <%= form_with url: add_recipe_recipe_list_path(@recipe_list, recipe_id: recipe.id), method: :post do |f| %>
            <%= f.label :recipe_list_id, "Select list to add to:" %>
            <%= f.select :recipe_list_id, options_for_select(@recipe_lists.collect { |list| [list.name, list.id]}), prompt: "Choose a list" %>
            <%= f.submit %>
          <% end %>
        </div>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/recipes/_searchbar.html.erb
<%= form_with url: search_recipes_path, method: :post do |form| %>
  <%= form.search_field :recipe_search, oninput: "this.form.requestSubmit()" %>
<% end %>

app/views/recipes/index.html.erb
<%= render "searchbar" %>
<%= render partial: "recipes/results", locals: { recipes: @recipes } %>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <div class="logo-container">
    <%= link_to root_path do %>
      <%= image_tag("logo.png", alt: "Home") %>
    <% end %>

    <%= link_to "My recipe lists", recipe_lists_path, class: "nav-link" %>
  </div>
</nav>